# Generated by Django 5.2.1 on 2025-05-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='affiliates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
